import type {Metadata} from 'next'
import './globals.css'
import React from "react";
import {newspaperColor} from "@/assets/color/color";
import {Layout} from "@/layout/layout";


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body style={{
            background: newspaperColor
        }}>
        <Layout>
            {children}
        </Layout>
        </body>
        </html>
    )
}
